In [1]:
import numpy as np
import json
import linecache
from scipy import sparse

In [2]:
def encode(labels):
    return (labels -100)/300
def decode(enc_labels):
    return (labels*300)+100

In [4]:
abatch_size = 5
number_to_train = 80
number_to_val   = 10
number_to_test  = 10
file_name = "features_binned_sparse_easy.txt"

In [ ]:
abatch_size = 25
number_to_train = 8000
number_to_val   = 1000
number_to_test  = 1000
file_name = "features_binned_sparse_easy.txt"

In [10]:
if False:
    js = linecache.getline("features_total_nu_hits2_easy.txt", 1)
    #print js
    features_binned_orig = np.array(json.loads(js))
    print features_binned_orig

In [13]:
def batch_generator_getline(batch_size=25, use_case='train'):
    assert use_case in ['train', 'val', 'test']
        
    if use_case == 'train':
        samples_per_epoch = number_to_train
        shuffle_index = np.arange(0, number_to_train)
    if use_case == 'val':
        samples_per_epoch = number_to_val
        shuffle_index = np.arange(number_to_train, number_to_train + number_to_val)
    if use_case == 'test':
        samples_per_epoch = number_to_test
        shuffle_index = np.arange(number_to_train + number_to_val, number_to_train + number_to_val + number_to_test)
    
    
    shape_3D = [15, 15, 25]
    number_of_batches = samples_per_epoch/batch_size
    counter=0
    
    np.random.shuffle(shuffle_index)
    
    #results_orig = np.load("results2_easy.npy")
    #results_enc = encode(results_orig) 

    while 1:
        index_batch = shuffle_index[batch_size*counter:batch_size*(counter+1)]
        for i, j in enumerate(index_batch):
            js = linecache.getline(file_name, j+1)
            l_js = js.split("\t")
            #print i, l_js
            
            data, indices, indptr, pvr_z_enc = l_js[0], l_js[1], l_js[2], l_js[3]
            #print indices
            indices = np.array(json.loads(indices));  indptr  = np.array(json.loads(indptr));  data    = np.array(json.loads(data)) 
            pvr_z_enc = np.array(json.loads(pvr_z_enc)) 
            sparse2 = sparse.csr_matrix((data, indices, indptr), shape=(shape_3D[0]*shape_3D[1], shape_3D[2]))
            dense2  = np.array(sparse2.todense()).reshape(shape_3D[0], shape_3D[1], shape_3D[2],1)

            if i == 0:
                features_binned = np.array([dense2])
                results_enc = np.array([pvr_z_enc])
            else:
                features_binned = np.append(features_binned, [dense2], axis=0)
                results_enc = np.append(results_enc, [pvr_z_enc])


        features_binned = features_binned.reshape(batch_size,shape_3D[0], shape_3D[1], shape_3D[2],1) 
        counter += 1
        yield(features_binned,results_enc)
        if (counter > number_of_batches):
            np.random.shuffle(shuffle_index)
            counter=0

In [5]:
def batch_generator_readlines(batch_size=25, use_case='train'):
    assert use_case in ['train', 'val', 'test']
        
    if use_case == 'train':
        samples_per_epoch = number_to_train
        shuffle_index = np.arange(0, number_to_train)
    if use_case == 'val':
        samples_per_epoch = number_to_val
        shuffle_index = np.arange(number_to_train, number_to_train + number_to_val)
    if use_case == 'test':
        samples_per_epoch = number_to_test
        shuffle_index = np.arange(number_to_train + number_to_val, number_to_train + number_to_val + number_to_test)
    
    
    shape_3D = [15, 15, 25]
    number_of_batches = samples_per_epoch/batch_size
    counter=0
    
    
    with open(file_name) as f_in:
        l_l_js = f_in.readlines()

        while 1:
            index_batch = shuffle_index[batch_size*counter:batch_size*(counter+1)]
            
            #print "counter : ", counter

            for i,j in enumerate(index_batch):

                l_js = l_l_js[j].split("\t")
                
                data, indices, indptr, pvr_z_enc = l_js[0], l_js[1], l_js[2], l_js[3]
                #print indices
                indices = np.array(json.loads(indices));  indptr  = np.array(json.loads(indptr));  data    = np.array(json.loads(data)) 
                pvr_z_enc = np.array(json.loads(pvr_z_enc)) 
                sparse2 = sparse.csr_matrix((data, indices, indptr), shape=(shape_3D[0]*shape_3D[1], shape_3D[2]))
                dense2  = np.array(sparse2.todense()).reshape(shape_3D[0], shape_3D[1], shape_3D[2],1)

                if i == 0:
                    features_binned = np.array([dense2])
                    results_enc = np.array([pvr_z_enc])
                else:
                    features_binned = np.append(features_binned, [dense2], axis=0)
                    results_enc = np.append(results_enc, [pvr_z_enc])


            
            features_binned = features_binned.reshape(batch_size,shape_3D[0], shape_3D[1], shape_3D[2],1) 
            counter += 1
            yield(features_binned,results_enc)
            if (counter > number_of_batches):
                np.random.shuffle(shuffle_index)
                counter=0

In [17]:
reader = batch_generator_readlines(abatch_size)
#reader = batch_generator_getline(abatch_size)
#reader = batch_generator_getline_backup(abatch_size)

print reader.next()
print "hi"

(array([[[[[ 0.],
          [ 0.],
          [ 0.],
          ..., 
          [ 0.],
          [ 0.],
          [ 0.]],

         [[ 0.],
          [ 0.],
          [ 0.],
          ..., 
          [ 0.],
          [ 0.],
          [ 0.]],

         [[ 0.],
          [ 0.],
          [ 0.],
          ..., 
          [ 0.],
          [ 0.],
          [ 0.]],

         ..., 
         [[ 0.],
          [ 0.],
          [ 0.],
          ..., 
          [ 0.],
          [ 0.],
          [ 0.]],

         [[ 0.],
          [ 0.],
          [ 0.],
          ..., 
          [ 0.],
          [ 0.],
          [ 0.]],

         [[ 0.],
          [ 0.],
          [ 0.],
          ..., 
          [ 0.],
          [ 0.],
          [ 0.]]],


        [[[ 0.],
          [ 0.],
          [ 0.],
          ..., 
          [ 0.],
          [ 0.],
          [ 0.]],

         [[ 0.],
          [ 0.],
          [ 0.],
          ..., 
          [ 0.],
          [ 0.],
          [ 0.]],

         [[ 0.],
     

In [7]:
def batch_generator_orig(X, y, batch_size):
    samples_per_epoch = X_data.shape[0]
    number_of_batches = samples_per_epoch/batch_size
    counter=0
    shuffle_index = np.arange(np.shape(y)[0])
    np.random.shuffle(shuffle_index)
    X =  X[shuffle_index, :]
    y =  y[shuffle_index]
    while 1:
        index_batch = shuffle_index[batch_size*counter:batch_size*(counter+1)]
        X_batch = X[index_batch,:].todense()
        y_batch = y[index_batch]
        counter += 1
        yield(np.array(X_batch),y_batch)
        if (counter > number_of_batches):
            np.random.shuffle(shuffle_index)
            counter=0

In [ ]:
#results_orig = np.load("results2_easy.npy")

In [8]:
if False:
    #features_binned = features_binned_orig.reshape([202,50,50,100,1])
    features_binned = features_binned_orig.reshape([10000,15,15,25,1])
    #features_binned = np.rollaxis(features_binned,0,5)
    results_enc = encode(results_orig) 

    print "features_binned.shape : ", features_binned.shape
    print "results.shape : ", results_enc.shape

In [ ]:
#features_binned_orig.shape



In [6]:
from keras.layers import Input, Dense, Dropout, Flatten 
from keras.layers import Conv3D, MaxPooling3D
from keras.models import Model



# This returns a tensor
#inputs = Input(shape=(50,50,100,))
inputs = Input(shape=(50,50,100,1,)) 
inputs = Input(shape=(15,15,25,1,)) 
#labels shape (,1)



x = Conv3D(4, (3, 3, 3), activation='relu')(inputs)
#x = MaxPooling3D(pool_size=(3,3,5))(x)
x = Conv3D(4, (3, 3, 5), activation='relu')(x)
x = Flatten()(x)




# a layer instance is callable on a tensor, and returns a tensor
x = Dense(256, activation='relu')(x)
x = Dense(64, activation='relu')(x)
predictions = Dense(1, activation='tanh')(x)

# This creates a model that includes
# the Input layer and three Dense layers
model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer='rmsprop',
              loss='mse',   #mean squared error
              metrics=[])


#model.fit_generator(generator=batch_generator_readlines(batch_size=abatch_size), steps_per_epoch=number_to_train/abatch_size, epochs=5)
model.fit_generator(generator=batch_generator_readlines(batch_size=abatch_size, use_case='train'), validation_data=batch_generator_readlines(batch_size=abatch_size, use_case='val'),
        validation_steps=number_to_val // abatch_size, steps_per_epoch=number_to_train//abatch_size, epochs=5)
#model.fit_generator(generator=batch_generator_getline(batch_size=abatch_size, use_case='train'), validation_data=batch_generator_getline(batch_size=abatch_size, use_case='val'),
#        validation_steps=number_to_val // abatch_size, steps_per_epoch=number_to_train//abatch_size, epochs=5)



#model.fit(features_binned[:number_to_train,:,:,:,:], results_enc[:number_to_train], epochs=5, batch_size=25)  # starts training

Using Theano backend.


Epoch 1/5
16/16 [==============================] - 8s - loss: 0.4753 - val_loss: 0.1270
Epoch 2/5
16/16 [==============================] - 7s - loss: 0.0780 - val_loss: 0.2024
Epoch 3/5
16/16 [==============================] - 7s - loss: 0.0502 - val_loss: 0.0877
Epoch 4/5
16/16 [==============================] - 7s - loss: 0.0307 - val_loss: 0.0826
Epoch 5/5
16/16 [==============================] - 7s - loss: 0.0190 - val_loss: 0.1071


In [8]:
score = model.evaluate_generator(generator=batch_generator_readlines(batch_size=abatch_size, use_case='test'), steps=number_to_test//abatch_size)
print score

0.116822108626


In [12]:
test_gen = batch_generator_readlines(batch_size=abatch_size, use_case='test')
counter = 0
max_test_steps = np.inf
for X, y in test_gen:
    if (counter >= min (number_to_test//abatch_size, max_test_steps) ): break
    counter += 1
    predicted = model.predict(X)
    comp = np.c_[y.reshape(-1,1), predicted]
    print comp

[[-0.33333333  0.03806866]
 [-0.33333333  0.03143368]
 [ 0.33333333  0.1810112 ]
 [-0.33333333 -0.03257972]
 [-0.33333333 -0.10960075]]
[[-0.33333333  0.09716488]
 [ 0.33333333  0.41681635]
 [-0.33333333 -0.06700287]
 [-0.33333333  0.1612725 ]
 [-0.33333333  0.14169362]]
